UserName: wing.nus@gmail.com
Password:
UserId: 105956
filePath: ../data/
activeCoursePageNum: 1
inactiveCoursePageNum: 25
dbPath: './coursera.db'
db1Path: './coursera1.db'
db2Path: './coursera2.db'
filePath: './data/'
